# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_lane.ui'
#
# Created: Thu May  8 12:56:05 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Lane(object):
    def setupUi(self, Lane):
        Lane.setObjectName(_fromUtf8("Lane"))
        Lane.setEnabled(True)
        Lane.resize(507, 436)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(13)
        Lane.setFont(font)
        Lane.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Lane.setWindowTitle(_fromUtf8("iSimGis Converter"))
        Lane.setWindowOpacity(4.0)
        Lane.setToolTip(_fromUtf8(""))
        Lane.setStatusTip(_fromUtf8(""))
        Lane.setSizeGripEnabled(False)
        self.gridLayout_3 = QtGui.QGridLayout(Lane)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.titleLabel = QtGui.QLabel(Lane)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.verticalLayout.addWidget(self.titleLabel)
        self.SegmentGroupBox = QtGui.QGroupBox(Lane)
        self.SegmentGroupBox.setObjectName(_fromUtf8("SegmentGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.SegmentGroupBox)
        self.gridLayout.setMargin(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.segmentIdLabel = QtGui.QLabel(self.SegmentGroupBox)
        self.segmentIdLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.segmentIdLabel.setObjectName(_fromUtf8("segmentIdLabel"))
        self.gridLayout.addWidget(self.segmentIdLabel, 0, 0, 1, 1)
        self.segmentId = QtGui.QLabel(self.SegmentGroupBox)
        self.segmentId.setText(_fromUtf8(""))
        self.segmentId.setObjectName(_fromUtf8("segmentId"))
        self.gridLayout.addWidget(self.segmentId, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.SegmentGroupBox)
        self.attributeGroup = QtGui.QGroupBox(Lane)
        self.attributeGroup.setTitle(_fromUtf8(""))
        self.attributeGroup.setObjectName(_fromUtf8("attributeGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.attributeGroup)
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.idLabel = QtGui.QLabel(self.attributeGroup)
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.horizontalLayout.addWidget(self.idLabel)
        self.id = QtGui.QLineEdit(self.attributeGroup)
        self.id.setObjectName(_fromUtf8("id"))
        self.horizontalLayout.addWidget(self.id)
        self.widthLabel = QtGui.QLabel(self.attributeGroup)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.horizontalLayout.addWidget(self.widthLabel)
        self.width = QtGui.QLineEdit(self.attributeGroup)
        self.width.setObjectName(_fromUtf8("width"))
        self.horizontalLayout.addWidget(self.width)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.can_go_straight = QtGui.QCheckBox(self.attributeGroup)
        self.can_go_straight.setObjectName(_fromUtf8("can_go_straight"))
        self.horizontalLayout_2.addWidget(self.can_go_straight)
        self.can_turn_left = QtGui.QCheckBox(self.attributeGroup)
        self.can_turn_left.setObjectName(_fromUtf8("can_turn_left"))
        self.horizontalLayout_2.addWidget(self.can_turn_left)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.can_turn_right = QtGui.QCheckBox(self.attributeGroup)
        self.can_turn_right.setObjectName(_fromUtf8("can_turn_right"))
        self.horizontalLayout_3.addWidget(self.can_turn_right)
        self.can_turn_on_red_signal = QtGui.QCheckBox(self.attributeGroup)
        self.can_turn_on_red_signal.setObjectName(_fromUtf8("can_turn_on_red_signal"))
        self.horizontalLayout_3.addWidget(self.can_turn_on_red_signal)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.can_change_lane_left = QtGui.QCheckBox(self.attributeGroup)
        self.can_change_lane_left.setObjectName(_fromUtf8("can_change_lane_left"))
        self.horizontalLayout_4.addWidget(self.can_change_lane_left)
        self.can_change_lane_right = QtGui.QCheckBox(self.attributeGroup)
        self.can_change_lane_right.setObjectName(_fromUtf8("can_change_lane_right"))
        self.horizontalLayout_4.addWidget(self.can_change_lane_right)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.is_road_shoulder = QtGui.QCheckBox(self.attributeGroup)
        self.is_road_shoulder.setObjectName(_fromUtf8("is_road_shoulder"))
        self.horizontalLayout_5.addWidget(self.is_road_shoulder)
        self.is_bicycle_lane = QtGui.QCheckBox(self.attributeGroup)
        self.is_bicycle_lane.setObjectName(_fromUtf8("is_bicycle_lane"))
        self.horizontalLayout_5.addWidget(self.is_bicycle_lane)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.is_pedestrian_lane = QtGui.QCheckBox(self.attributeGroup)
        self.is_pedestrian_lane.setObjectName(_fromUtf8("is_pedestrian_lane"))
        self.horizontalLayout_6.addWidget(self.is_pedestrian_lane)
        self.is_vehicle_lane = QtGui.QCheckBox(self.attributeGroup)
        self.is_vehicle_lane.setObjectName(_fromUtf8("is_vehicle_lane"))
        self.horizontalLayout_6.addWidget(self.is_vehicle_lane)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.is_standard_bus_lane = QtGui.QCheckBox(self.attributeGroup)
        self.is_standard_bus_lane.setObjectName(_fromUtf8("is_standard_bus_lane"))
        self.horizontalLayout_7.addWidget(self.is_standard_bus_lane)
        self.is_whole_day_bus_lane = QtGui.QCheckBox(self.attributeGroup)
        self.is_whole_day_bus_lane.setObjectName(_fromUtf8("is_whole_day_bus_lane"))
        self.horizontalLayout_7.addWidget(self.is_whole_day_bus_lane)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.is_high_occupancy_vehicle_lane = QtGui.QCheckBox(self.attributeGroup)
        self.is_high_occupancy_vehicle_lane.setObjectName(_fromUtf8("is_high_occupancy_vehicle_lane"))
        self.horizontalLayout_8.addWidget(self.is_high_occupancy_vehicle_lane)
        self.can_freely_park_here = QtGui.QCheckBox(self.attributeGroup)
        self.can_freely_park_here.setObjectName(_fromUtf8("can_freely_park_here"))
        self.horizontalLayout_8.addWidget(self.can_freely_park_here)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.can_stop_here = QtGui.QCheckBox(self.attributeGroup)
        self.can_stop_here.setObjectName(_fromUtf8("can_stop_here"))
        self.horizontalLayout_9.addWidget(self.can_stop_here)
        self.is_u_turn_allowed = QtGui.QCheckBox(self.attributeGroup)
        self.is_u_turn_allowed.setObjectName(_fromUtf8("is_u_turn_allowed"))
        self.horizontalLayout_9.addWidget(self.is_u_turn_allowed)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 8, 0, 1, 1)
        self.verticalLayout.addWidget(self.attributeGroup)
        self.splitter = QtGui.QSplitter(Lane)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.errorMessage = QtGui.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setItalic(True)
        self.errorMessage.setFont(font)
        self.errorMessage.setStyleSheet(_fromUtf8("color: rgb(255, 20, 27)"))
        self.errorMessage.setText(_fromUtf8(""))
        self.errorMessage.setObjectName(_fromUtf8("errorMessage"))
        self.actionButton = QtGui.QPushButton(self.splitter)
        self.actionButton.setMaximumSize(QtCore.QSize(100, 100))
        self.actionButton.setObjectName(_fromUtf8("actionButton"))
        self.verticalLayout.addWidget(self.splitter)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Lane)
        QtCore.QMetaObject.connectSlotsByName(Lane)

    def retranslateUi(self, Lane):
        self.titleLabel.setText(_translate("Lane", "LANE", None))
        self.SegmentGroupBox.setTitle(_translate("Lane", "Segment", None))
        self.segmentIdLabel.setText(_translate("Lane", "SegmentId*", None))
        self.idLabel.setText(_translate("Lane", "Id*", None))
        self.widthLabel.setText(_translate("Lane", "Width*", None))
        self.can_go_straight.setText(_translate("Lane", "can_go_straight", None))
        self.can_turn_left.setText(_translate("Lane", "can_turn_left", None))
        self.can_turn_right.setText(_translate("Lane", "can_turn_right", None))
        self.can_turn_on_red_signal.setText(_translate("Lane", "can_turn_on_red_signal", None))
        self.can_change_lane_left.setText(_translate("Lane", "can_change_lane_left", None))
        self.can_change_lane_right.setText(_translate("Lane", "can_change_lane_right", None))
        self.is_road_shoulder.setText(_translate("Lane", "is_road_shoulder", None))
        self.is_bicycle_lane.setText(_translate("Lane", "is_bicycle_lane", None))
        self.is_pedestrian_lane.setText(_translate("Lane", "is_pedestrian_lane", None))
        self.is_vehicle_lane.setText(_translate("Lane", "is_vehicle_lane", None))
        self.is_standard_bus_lane.setText(_translate("Lane", "is_standard_bus_lane", None))
        self.is_whole_day_bus_lane.setText(_translate("Lane", "is_whole_day_bus_lane", None))
        self.is_high_occupancy_vehicle_lane.setText(_translate("Lane", "is_high_occupancy_vehicle_lane", None))
        self.can_freely_park_here.setText(_translate("Lane", "can_freely_park_here", None))
        self.can_stop_here.setText(_translate("Lane", "can_stop_here", None))
        self.is_u_turn_allowed.setText(_translate("Lane", "is_u_turn_allowed", None))
        self.actionButton.setText(_translate("Lane", "ADD", None))

