# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_segment.ui'
#
# Created: Thu May  8 12:39:47 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Segment(object):
    def setupUi(self, Segment):
        Segment.setObjectName(_fromUtf8("Segment"))
        Segment.setEnabled(True)
        Segment.resize(481, 331)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(13)
        Segment.setFont(font)
        Segment.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Segment.setWindowTitle(_fromUtf8("iSimGis Converter"))
        Segment.setWindowOpacity(4.0)
        Segment.setToolTip(_fromUtf8(""))
        Segment.setStatusTip(_fromUtf8(""))
        Segment.setSizeGripEnabled(False)
        self.gridLayout_3 = QtGui.QGridLayout(Segment)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.titleLabel = QtGui.QLabel(Segment)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.verticalLayout.addWidget(self.titleLabel)
        self.linkGroupBox = QtGui.QGroupBox(Segment)
        self.linkGroupBox.setTitle(_fromUtf8(""))
        self.linkGroupBox.setObjectName(_fromUtf8("linkGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.linkGroupBox)
        self.gridLayout.setMargin(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.linkGroupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.linkIdLabel = QtGui.QLabel(self.splitter)
        self.linkIdLabel.setObjectName(_fromUtf8("linkIdLabel"))
        self.linkIdComboBox = QtGui.QComboBox(self.splitter)
        self.linkIdComboBox.setObjectName(_fromUtf8("linkIdComboBox"))
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.linkName = QtGui.QLabel(self.linkGroupBox)
        self.linkName.setText(_fromUtf8(""))
        self.linkName.setObjectName(_fromUtf8("linkName"))
        self.gridLayout.addWidget(self.linkName, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.linkGroupBox)
        self.attributeGroup = QtGui.QGroupBox(Segment)
        self.attributeGroup.setTitle(_fromUtf8(""))
        self.attributeGroup.setObjectName(_fromUtf8("attributeGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.attributeGroup)
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.idLabel = QtGui.QLabel(self.attributeGroup)
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.horizontalLayout.addWidget(self.idLabel)
        self.id = QtGui.QLineEdit(self.attributeGroup)
        self.id.setObjectName(_fromUtf8("id"))
        self.horizontalLayout.addWidget(self.id)
        self.aimsunIdLabel = QtGui.QLabel(self.attributeGroup)
        self.aimsunIdLabel.setObjectName(_fromUtf8("aimsunIdLabel"))
        self.horizontalLayout.addWidget(self.aimsunIdLabel)
        self.aimsunId = QtGui.QLineEdit(self.attributeGroup)
        self.aimsunId.setObjectName(_fromUtf8("aimsunId"))
        self.horizontalLayout.addWidget(self.aimsunId)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.startNodeLabel = QtGui.QLabel(self.attributeGroup)
        self.startNodeLabel.setObjectName(_fromUtf8("startNodeLabel"))
        self.horizontalLayout_2.addWidget(self.startNodeLabel)
        self.startNode = QtGui.QLineEdit(self.attributeGroup)
        self.startNode.setObjectName(_fromUtf8("startNode"))
        self.horizontalLayout_2.addWidget(self.startNode)
        self.endNodeLabel = QtGui.QLabel(self.attributeGroup)
        self.endNodeLabel.setObjectName(_fromUtf8("endNodeLabel"))
        self.horizontalLayout_2.addWidget(self.endNodeLabel)
        self.endNode = QtGui.QLineEdit(self.attributeGroup)
        self.endNode.setObjectName(_fromUtf8("endNode"))
        self.horizontalLayout_2.addWidget(self.endNode)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.maxSpeedLabel = QtGui.QLabel(self.attributeGroup)
        self.maxSpeedLabel.setObjectName(_fromUtf8("maxSpeedLabel"))
        self.horizontalLayout_3.addWidget(self.maxSpeedLabel)
        self.maxSpeed = QtGui.QLineEdit(self.attributeGroup)
        self.maxSpeed.setObjectName(_fromUtf8("maxSpeed"))
        self.horizontalLayout_3.addWidget(self.maxSpeed)
        self.lengthLabel = QtGui.QLabel(self.attributeGroup)
        self.lengthLabel.setObjectName(_fromUtf8("lengthLabel"))
        self.horizontalLayout_3.addWidget(self.lengthLabel)
        self.length = QtGui.QLineEdit(self.attributeGroup)
        self.length.setObjectName(_fromUtf8("length"))
        self.horizontalLayout_3.addWidget(self.length)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widthLabel = QtGui.QLabel(self.attributeGroup)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.horizontalLayout_4.addWidget(self.widthLabel)
        self.width = QtGui.QLineEdit(self.attributeGroup)
        self.width.setObjectName(_fromUtf8("width"))
        self.horizontalLayout_4.addWidget(self.width)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.attributeGroup)
        self.splitter_2 = QtGui.QSplitter(Segment)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.errorMessage = QtGui.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.errorMessage.setFont(font)
        self.errorMessage.setStyleSheet(_fromUtf8("color: rgb(255, 20, 27)"))
        self.errorMessage.setText(_fromUtf8(""))
        self.errorMessage.setObjectName(_fromUtf8("errorMessage"))
        self.actionButton = QtGui.QPushButton(self.splitter_2)
        self.actionButton.setMaximumSize(QtCore.QSize(100, 100))
        self.actionButton.setObjectName(_fromUtf8("actionButton"))
        self.verticalLayout.addWidget(self.splitter_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Segment)
        QtCore.QMetaObject.connectSlotsByName(Segment)

    def retranslateUi(self, Segment):
        self.titleLabel.setText(_translate("Segment", "SEGMENT", None))
        self.linkIdLabel.setText(_translate("Segment", "LinkId*", None))
        self.idLabel.setText(_translate("Segment", "Id*", None))
        self.aimsunIdLabel.setText(_translate("Segment", "Aimsun Id*", None))
        self.startNodeLabel.setText(_translate("Segment", "StartNode*", None))
        self.endNodeLabel.setText(_translate("Segment", "EndNode*", None))
        self.maxSpeedLabel.setText(_translate("Segment", "MaxSpeed*", None))
        self.lengthLabel.setText(_translate("Segment", "Length*", None))
        self.widthLabel.setText(_translate("Segment", "Width*", None))
        self.actionButton.setText(_translate("Segment", "ADD", None))

