# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_converter.ui'
#
# Created: Thu May  8 13:04:46 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Converter(object):
    def setupUi(self, Converter):
        Converter.setObjectName(_fromUtf8("Converter"))
        Converter.setEnabled(True)
        Converter.resize(701, 300)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(12)
        Converter.setFont(font)
        Converter.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Converter.setWindowTitle(_fromUtf8("iSimGis Converter"))
        Converter.setWindowOpacity(4.0)
        Converter.setToolTip(_fromUtf8(""))
        Converter.setStatusTip(_fromUtf8(""))
        Converter.setSizeGripEnabled(False)
        self.tabWidget = QtGui.QTabWidget(Converter)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 661, 271))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.XMLtoSH = QtGui.QWidget()
        self.XMLtoSH.setObjectName(_fromUtf8("XMLtoSH"))
        self.xmlsh_converter_but = QtGui.QPushButton(self.XMLtoSH)
        self.xmlsh_converter_but.setGeometry(QtCore.QRect(240, 154, 181, 35))
        self.xmlsh_converter_but.setObjectName(_fromUtf8("xmlsh_converter_but"))
        self.xmlsh_progress = QtGui.QProgressBar(self.XMLtoSH)
        self.xmlsh_progress.setGeometry(QtCore.QRect(50, 205, 561, 23))
        self.xmlsh_progress.setProperty("value", 0)
        self.xmlsh_progress.setObjectName(_fromUtf8("xmlsh_progress"))
        self.xmlsh_status = QtGui.QLabel(self.XMLtoSH)
        self.xmlsh_status.setGeometry(QtCore.QRect(30, 205, 601, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(13)
        font.setItalic(True)
        self.xmlsh_status.setFont(font)
        self.xmlsh_status.setText(_fromUtf8(""))
        self.xmlsh_status.setAlignment(QtCore.Qt.AlignCenter)
        self.xmlsh_status.setObjectName(_fromUtf8("xmlsh_status"))
        self.widget = QtGui.QWidget(self.XMLtoSH)
        self.widget.setGeometry(QtCore.QRect(10, 10, 641, 25))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.xmlsh_xml_label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.xmlsh_xml_label.setFont(font)
        self.xmlsh_xml_label.setObjectName(_fromUtf8("xmlsh_xml_label"))
        self.horizontalLayout.addWidget(self.xmlsh_xml_label)
        self.xmlsh_xml_path = QtGui.QLineEdit(self.widget)
        self.xmlsh_xml_path.setEnabled(False)
        self.xmlsh_xml_path.setObjectName(_fromUtf8("xmlsh_xml_path"))
        self.horizontalLayout.addWidget(self.xmlsh_xml_path)
        self.xmlsh_xml_browser = QtGui.QToolButton(self.widget)
        self.xmlsh_xml_browser.setObjectName(_fromUtf8("xmlsh_xml_browser"))
        self.horizontalLayout.addWidget(self.xmlsh_xml_browser)
        self.widget1 = QtGui.QWidget(self.XMLtoSH)
        self.widget1.setGeometry(QtCore.QRect(10, 50, 641, 25))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.xmlsh_sh_label = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.xmlsh_sh_label.setFont(font)
        self.xmlsh_sh_label.setObjectName(_fromUtf8("xmlsh_sh_label"))
        self.horizontalLayout_2.addWidget(self.xmlsh_sh_label)
        self.xmlsh_sh_path = QtGui.QLineEdit(self.widget1)
        self.xmlsh_sh_path.setEnabled(False)
        self.xmlsh_sh_path.setObjectName(_fromUtf8("xmlsh_sh_path"))
        self.horizontalLayout_2.addWidget(self.xmlsh_sh_path)
        self.xmlsh_sh_browser = QtGui.QToolButton(self.widget1)
        self.xmlsh_sh_browser.setObjectName(_fromUtf8("xmlsh_sh_browser"))
        self.horizontalLayout_2.addWidget(self.xmlsh_sh_browser)
        self.widget2 = QtGui.QWidget(self.XMLtoSH)
        self.widget2.setGeometry(QtCore.QRect(10, 100, 641, 23))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.xmlsh_formula_l1 = QtGui.QLabel(self.widget2)
        self.xmlsh_formula_l1.setObjectName(_fromUtf8("xmlsh_formula_l1"))
        self.horizontalLayout_3.addWidget(self.xmlsh_formula_l1)
        self.xmlsh_formula_l2 = QtGui.QLabel(self.widget2)
        self.xmlsh_formula_l2.setObjectName(_fromUtf8("xmlsh_formula_l2"))
        self.horizontalLayout_3.addWidget(self.xmlsh_formula_l2)
        self.xmlsh_formula_x = QtGui.QLineEdit(self.widget2)
        self.xmlsh_formula_x.setEnabled(True)
        self.xmlsh_formula_x.setObjectName(_fromUtf8("xmlsh_formula_x"))
        self.horizontalLayout_3.addWidget(self.xmlsh_formula_x)
        self.xmlsh_formula_l3 = QtGui.QLabel(self.widget2)
        self.xmlsh_formula_l3.setObjectName(_fromUtf8("xmlsh_formula_l3"))
        self.horizontalLayout_3.addWidget(self.xmlsh_formula_l3)
        self.xmlsh_formula_y = QtGui.QLineEdit(self.widget2)
        self.xmlsh_formula_y.setEnabled(True)
        self.xmlsh_formula_y.setObjectName(_fromUtf8("xmlsh_formula_y"))
        self.horizontalLayout_3.addWidget(self.xmlsh_formula_y)
        self.xmlsh_formula_l4 = QtGui.QLabel(self.widget2)
        self.xmlsh_formula_l4.setObjectName(_fromUtf8("xmlsh_formula_l4"))
        self.horizontalLayout_3.addWidget(self.xmlsh_formula_l4)
        self.tabWidget.addTab(self.XMLtoSH, _fromUtf8(""))
        self.SHtoXML = QtGui.QWidget()
        self.SHtoXML.setObjectName(_fromUtf8("SHtoXML"))
        self.shxml_status = QtGui.QLabel(self.SHtoXML)
        self.shxml_status.setGeometry(QtCore.QRect(20, 205, 611, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(13)
        font.setItalic(True)
        self.shxml_status.setFont(font)
        self.shxml_status.setText(_fromUtf8(""))
        self.shxml_status.setAlignment(QtCore.Qt.AlignCenter)
        self.shxml_status.setObjectName(_fromUtf8("shxml_status"))
        self.shxml_converter_but = QtGui.QPushButton(self.SHtoXML)
        self.shxml_converter_but.setGeometry(QtCore.QRect(241, 154, 181, 35))
        self.shxml_converter_but.setObjectName(_fromUtf8("shxml_converter_but"))
        self.shxml_progress = QtGui.QProgressBar(self.SHtoXML)
        self.shxml_progress.setGeometry(QtCore.QRect(50, 205, 561, 23))
        self.shxml_progress.setProperty("value", 0)
        self.shxml_progress.setObjectName(_fromUtf8("shxml_progress"))
        self.widget3 = QtGui.QWidget(self.SHtoXML)
        self.widget3.setGeometry(QtCore.QRect(10, 10, 641, 25))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.shxml_sh_label = QtGui.QLabel(self.widget3)
        self.shxml_sh_label.setObjectName(_fromUtf8("shxml_sh_label"))
        self.horizontalLayout_4.addWidget(self.shxml_sh_label)
        self.shxml_sh_path = QtGui.QLineEdit(self.widget3)
        self.shxml_sh_path.setEnabled(False)
        self.shxml_sh_path.setObjectName(_fromUtf8("shxml_sh_path"))
        self.horizontalLayout_4.addWidget(self.shxml_sh_path)
        self.shxml_sh_browser = QtGui.QToolButton(self.widget3)
        self.shxml_sh_browser.setObjectName(_fromUtf8("shxml_sh_browser"))
        self.horizontalLayout_4.addWidget(self.shxml_sh_browser)
        self.widget4 = QtGui.QWidget(self.SHtoXML)
        self.widget4.setGeometry(QtCore.QRect(10, 50, 641, 25))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.shxml_xml_label = QtGui.QLabel(self.widget4)
        self.shxml_xml_label.setObjectName(_fromUtf8("shxml_xml_label"))
        self.horizontalLayout_5.addWidget(self.shxml_xml_label)
        self.shxml_xml_path = QtGui.QLineEdit(self.widget4)
        self.shxml_xml_path.setEnabled(False)
        self.shxml_xml_path.setObjectName(_fromUtf8("shxml_xml_path"))
        self.horizontalLayout_5.addWidget(self.shxml_xml_path)
        self.shxml_xml_browser = QtGui.QToolButton(self.widget4)
        self.shxml_xml_browser.setObjectName(_fromUtf8("shxml_xml_browser"))
        self.horizontalLayout_5.addWidget(self.shxml_xml_browser)
        self.widget5 = QtGui.QWidget(self.SHtoXML)
        self.widget5.setGeometry(QtCore.QRect(10, 100, 641, 23))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.shxml_formula_l1 = QtGui.QLabel(self.widget5)
        self.shxml_formula_l1.setObjectName(_fromUtf8("shxml_formula_l1"))
        self.horizontalLayout_6.addWidget(self.shxml_formula_l1)
        self.shxml_formula_l2 = QtGui.QLabel(self.widget5)
        self.shxml_formula_l2.setObjectName(_fromUtf8("shxml_formula_l2"))
        self.horizontalLayout_6.addWidget(self.shxml_formula_l2)
        self.shxml_formula_x = QtGui.QLineEdit(self.widget5)
        self.shxml_formula_x.setEnabled(True)
        self.shxml_formula_x.setObjectName(_fromUtf8("shxml_formula_x"))
        self.horizontalLayout_6.addWidget(self.shxml_formula_x)
        self.shxml_formula_l3 = QtGui.QLabel(self.widget5)
        self.shxml_formula_l3.setObjectName(_fromUtf8("shxml_formula_l3"))
        self.horizontalLayout_6.addWidget(self.shxml_formula_l3)
        self.shxml_formula_y = QtGui.QLineEdit(self.widget5)
        self.shxml_formula_y.setEnabled(True)
        self.shxml_formula_y.setObjectName(_fromUtf8("shxml_formula_y"))
        self.horizontalLayout_6.addWidget(self.shxml_formula_y)
        self.shxml_formula_l4 = QtGui.QLabel(self.widget5)
        self.shxml_formula_l4.setObjectName(_fromUtf8("shxml_formula_l4"))
        self.horizontalLayout_6.addWidget(self.shxml_formula_l4)
        self.tabWidget.addTab(self.SHtoXML, _fromUtf8(""))

        self.retranslateUi(Converter)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Converter)

    def retranslateUi(self, Converter):
        self.xmlsh_converter_but.setText(_translate("Converter", "XML TO SHAPEFILES", None))
        self.xmlsh_xml_label.setText(_translate("Converter", "iSim XML File", None))
        self.xmlsh_xml_browser.setText(_translate("Converter", "...", None))
        self.xmlsh_sh_label.setText(_translate("Converter", "Destination Dir", None))
        self.xmlsh_sh_browser.setText(_translate("Converter", "...", None))
        self.xmlsh_formula_l1.setText(_translate("Converter", "Coordinate Conversion Formula", None))
        self.xmlsh_formula_l2.setText(_translate("Converter", "[ x\' = ", None))
        self.xmlsh_formula_x.setText(_translate("Converter", "x", None))
        self.xmlsh_formula_l3.setText(_translate("Converter", ", y\' = ", None))
        self.xmlsh_formula_y.setText(_translate("Converter", "y", None))
        self.xmlsh_formula_l4.setText(_translate("Converter", "]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.XMLtoSH), _translate("Converter", "XML to Shapefiles", None))
        self.shxml_converter_but.setText(_translate("Converter", "SHAPEFILES TO XML", None))
        self.shxml_sh_label.setText(_translate("Converter", "Shapefiles Dir", None))
        self.shxml_sh_browser.setText(_translate("Converter", "...", None))
        self.shxml_xml_label.setText(_translate("Converter", "XML output", None))
        self.shxml_xml_browser.setText(_translate("Converter", "...", None))
        self.shxml_formula_l1.setText(_translate("Converter", "Coordinate Conversion Formula", None))
        self.shxml_formula_l2.setText(_translate("Converter", "[ x\' = ", None))
        self.shxml_formula_x.setText(_translate("Converter", "x", None))
        self.shxml_formula_l3.setText(_translate("Converter", ", y\' = ", None))
        self.shxml_formula_y.setText(_translate("Converter", "y", None))
        self.shxml_formula_l4.setText(_translate("Converter", "]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SHtoXML), _translate("Converter", "Shapefiles to XML", None))

